schemaFile: http://localhost:8000/openapi.json # Upewnij się, że port jest prawidłowy
apiFile: ./src/store/api.ts
apiImport: baseApi
outputFile: ./src/store/generated.ts
exportName: api
hooks: true

# Opcjonalnie możesz dodać debugowanie
debug: true
verbose: true
